apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: expense-1
  region: us-east-1a
managedNodeGroups:
  - name: expense
    desiredCapacity: 3
    instanceType: m5.large
    spot: true